---
pipeline: 2019_07_11_JUMP-CP
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments: cells,cytoplasm,nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  features: infer
annotate:
  perform: true
  well_column: Metadata_Well
  external : JUMP-Target-2_compound_metadata.tsv
normalize:
  perform: true
  method: mad_robustize
  features: infer
  negcon: true
feature_select:
  perform: true
  features: infer
  negcon: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_04_20_Target2
plates:
  - name: BR00121431
    process: true
  - name: BR00121432
    process: true
  - name: BR00121433
    process: true
  - name: BR00121434
    process: true
  - name: BR00121435
    process: true
  - name: BR00121440
    process: true
process: true
